security:
  jwt:
    token:
      secret-key: 54cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Locadora_Veiculos_2023?useTimezone=true&serverTimezone=UTC
    username: root
    password: 939345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
springdoc:
  swagger-ui:
    use-root-path: true

      #server:
      # servlet:
    #   contextPath: /Locadora